//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gai.Entitis
{
    using System;
    using System.Collections.Generic;
    
    public partial class drivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public drivers()
        {
            this.Gai_licence = new HashSet<licence>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sername { get; set; }
        public string Middlename { get; set; }
        public Nullable<int> PasportSeria { get; set; }
        public Nullable<int> PasportNumber { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string Address { get; set; }
        public string AddresLife { get; set; }
        public string Company { get; set; }
        public string Jobname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public string Fio
        {
            get
            {
                return Sername + " " + Name + " " + Middlename;
            }
        }
        public string SecondPhoto
        {
            get
            {
                return "";
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<licence> Gai_licence { get; set; }
    }
}
