//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gai.Entitis
{
    using System;
    using System.Collections.Generic;
    
    public partial class licence
    {
        public int Id { get; set; }
        public int LicenceSeries { get; set; }
        public int LicenceNumber { get; set; }
        public System.DateTime LicenceDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int Driverid { get; set; }
        public int Categories { get; set; }
        public Nullable<int> Statys { get; set; }
        public string Comment { get; set; }
        public string DriverSername
        {
            get
            {
                return Gai_drivers.Sername;
            }
        }
        public string DriverNameOtchestvo
        {
            get
            {
                return Gai_drivers.Name+" "+Gai_drivers.Middlename;
            }
        }
        public string DateOfBirthday 
        {
            get
            {
                return "22.04.2002";
            }
        }
        public string PlaceOfBirthday
        {
            get
            {
                return Gai_drivers.Address;
            }
        }
        public string Date
        {
            get
            {
                return LicenceDate.Date.ToShortDateString()+"        "+ExpireDate.Date.ToShortDateString();
            }
        }
        public string LichesSeriaNumber
        {
            get
            {
                return LicenceSeries.ToString() + "  " + LicenceNumber.ToString();
            }
        }
        public string Categotia
        {
            get
            {
                return Gai_categories.Name;
            }
        }
        public string Photo
        {
            get
            {
                return "Photo\\" + Gai_drivers.Photo;
            }
        }


        public virtual categories Gai_categories { get; set; }
        public virtual drivers Gai_drivers { get; set; }
        public virtual status Gai_status { get; set; }
    }
}
